#pragma once
#include "MidiSettings.h"
#include "SoundBankPanel.h"
#include "TransportPanel.h"
#include "MidiCanvas/MidiCanvas.h"
#include "Log.h"
#include "UndoHistoryPanel.h"
#include "ShortcutsPanel.h"
#include "DrumMachine/DrumMachinePanel.h"
