#pragma once
#include "Dummy.h"
#include "MidiSettings.h"
#include "ChannelControls.h"
#include "SoundBankPanel.h"
#include "TransportPanel.h"
#include "MidiCanvas.h"
#include "Log.h"
#include "UndoHistoryPanel.h"
