#pragma once
#include <wx/wx.h>

// Custom wxWidgets IDs for MainFrame
enum MainFrameIDs
{
	// Keyboard shortcuts
	ID_KEYBOARD_TOGGLE_PLAY = wxID_HIGHEST + 1000,
	ID_KEYBOARD_RECORD,
	ID_KEYBOARD_QUANTIZE,
    ID_KEYBOARD_PREVIOUS_MEASURE,
    ID_KEYBOARD_NEXT_MEASURE,

	// Drum pad triggers (1-0 keys)
	ID_KEYBOARD_DRUM_PAD_1,
	ID_KEYBOARD_DRUM_PAD_2,
	ID_KEYBOARD_DRUM_PAD_3,
	ID_KEYBOARD_DRUM_PAD_4,
	ID_KEYBOARD_DRUM_PAD_5,
	ID_KEYBOARD_DRUM_PAD_6,
	ID_KEYBOARD_DRUM_PAD_7,
	ID_KEYBOARD_DRUM_PAD_8,
	ID_KEYBOARD_DRUM_PAD_9,
	ID_KEYBOARD_DRUM_PAD_0,

	// Midi file Import/Export
	ID_MENU_IMPORT_MIDIFILE, 
	ID_MENU_EXPORT_MIDIFILE,
	
	// Panel menu IDs (dynamically assigned starting here)
	ID_PANELS_BEGIN
};


